### ISSUE TITLE
generateCohortSet error

### ISSUE THREAD

**Issue by rfherrerac** [OdyOSG/CDMConnector#12] opened 2023-03-02 04:56 UTC
When using the generateCohortSet function, seems like the internal function Inschema is not compatible with the DBI function dbCreateTable. 
Within the function generateCohortSet  line 186 when reaching this part: 
DBI::dbCreateTable(con
                   name =  inSchema(writeSchema, name),
                   fields = c(
                     cohort_definition_id = "INT",
                     subject_id = "INT",
                     cohort_start_date = "DATE",
                     cohort_end_date = "DATE"
                   ))

I am getting 

Error in as.character.default(x) :
no method for coercing this S4 class to a vector

**Comment by ablack3** [comment] 2023-03-08 04:26
Thanks for reporting this. Will you try using the latest development version?

`remotes::install_github("OdyOSG/CDMConnector")`

If the issue is fixed will you close this issue as completed?

If you still get the error will you post a reprex using the R [reprex](https://reprex.tidyverse.org/) package?

Here is an example reprex showing this working on Postgres.

``` r
con <- DBI::dbConnect(RPostgres::Postgres(),
                        dbname = Sys.getenv("LOCAL_POSTGRESQL_DBNAME"),
                        host = Sys.getenv("LOCAL_POSTGRESQL_HOST"),
                        user = Sys.getenv("LOCAL_POSTGRESQL_USER"),
                        password = Sys.getenv("LOCAL_POSTGRESQL_PASSWORD"))
                        
DBI::dbCreateTable(con,
                   name = CDMConnector:::inSchema("scratch", "test_cohort"),
                   fields = c(
                     cohort_definition_id = "INT",
                     subject_id = "INT",
                     cohort_start_date = "DATE",
                     cohort_end_date = "DATE"
                   ))

tibble::tibble(
  DBI::dbReadTable(con, CDMConnector:::inSchema("scratch", "test_cohort"))
)
#> # A tibble: 0 × 4
#> # … with 4 variables: cohort_definition_id <int>, subject_id <int>,
#> #   cohort_start_date <date>, cohort_end_date <date>

DBI::dbRemoveTable(con, CDMConnector:::inSchema("scratch", "test_cohort"))

DBI::dbDisconnect(con)
```

<sup>Created on 2023-03-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Closed** 2023-03-25 19:11 UTC
